FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt -y install software-properties-common \
    && add-apt-repository -y cloud-archive:wallaby \
    && apt update && apt -y upgrade \
    && apt -y install python3 python3-openstackclient python3-oauth2client python3-pymysql git python3-pip


àhjspdiòh;oắdibfgaedfn'ưepònkl